# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'aquareg'
        command: 'login'
    - task: aquasecScanner@4
      inputs:
        image: '$(imagename):$(tag)'
        scanType: 'hosted'
        register: true
        hideBase: false
        showNegligible: false
        windowsScannerVersion: '6.5.0'
        scanner: 'registry.aquasec.com/scanner:2022.4.261'
        runOptions: '-e AQUA_TOKEN=7bf6d0392fcfb6cea1ca5364a65583d556ab92a3'
        registry: 'Docker Hub'
        connection: 'aqua'
        customFlags: '--direct-cc'